### ISSUE TITLE
'Bunch' object has no attribute 'node_dim'

### ISSUE THREAD

**Issue by sxue2** [freesunshine0316/nary-grn#6]
Number of words: 2662
Number of allChars: 100
Number of allEdgelabels: 109
word vocab size 15736
Build DataStream ... 
Number of instances in trainDataStream: 505
Number of instances in devDataStream: 200
Number of batches in trainDataStream: 64
Number of batches in devDataStream: 25
Traceback (most recent call last):
  File "G2S_trainer.py", line 285, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/shangxue/Documents/Projects/NLP/myRelationTraining/nary-IBM/nary-grn/gs_lstm/venv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "G2S_trainer.py", line 174, in main
    char_vocab=char_vocab, options=FLAGS, mode='train')
  File "/Users/shangxue/Documents/Projects/NLP/myRelationTraining/nary-IBM/nary-grn/gs_lstm/G2S_model_graph.py", line 74, in __init__
    self.encoder_dim = options.neighbor_vector_dim + options.node_dim
AttributeError: 'Bunch' object has no attribute 'node_dim'

Could you please help on this issue?

**Comment by freesunshine0316** [comment]
I've fixed it.

**Comment by sxue2** [comment]
Traceback (most recent call last):
  File "G2S_trainer.py", line 285, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/shangxue/Documents/Projects/NLP/myRelationTraining/nary-IBM/nary-grn/gs_lstm/venv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "G2S_trainer.py", line 174, in main
    char_vocab=char_vocab, options=FLAGS, mode='train')
  File "/Users/shangxue/Documents/Projects/NLP/myRelationTraining/nary-IBM/nary-grn/gs_lstm/G2S_model_graph.py", line 74, in __init__
    self.encoder_dim = options.neighbor_vector_dim + self.input_dim
AttributeError: 'ModelGraph' object has no attribute 'input_dim

Could you please check? Thank you.

**Comment by freesunshine0316** [comment]
fixed.

**Comment by sxue2** [comment]
Works great. It is able to train now.
